// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using t5_back.Data;

#nullable disable

namespace t5_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119102755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("t5_back.Models.Equipment", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("RemainingStock")
                        .HasColumnType("REAL");

                    b.Property<float?>("TotalStock")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("t5_back.Models.Event", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsibleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("UUID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("t5_back.Models.ImagePoint", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PointId")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId", "PointId");

                    b.HasIndex("PointId");

                    b.ToTable("ImagePoints");
                });

            modelBuilder.Entity("t5_back.Models.Photo", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("UUID");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EventId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("t5_back.Models.ImagePoint", b =>
                {
                    b.HasOne("t5_back.Models.Photo", "Photo")
                        .WithMany("ImagePoints")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("t5_back.Models.Point", "Point")
                        .WithMany("ImagePoints")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.HasOne("t5_back.Models.Equipment", "Equipment")
                        .WithMany("Points")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("t5_back.Models.Event", "Event")
                        .WithMany("Points")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("t5_back.Models.Equipment", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("t5_back.Models.Event", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("t5_back.Models.Photo", b =>
                {
                    b.Navigation("ImagePoints");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.Navigation("ImagePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
