// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using t5_back.Data;

#nullable disable

namespace t5_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("t5_back.Models.Equipement", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Stock_restant")
                        .HasColumnType("REAL");

                    b.Property<float?>("Stock_total")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("t5_back.Models.Evenement", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date_debut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Responsable")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("t5_back.Models.Image_Point", b =>
                {
                    b.Property<Guid>("Image_ID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Point_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("Image_ID", "Point_ID");

                    b.HasIndex("Point_ID");

                    b.ToTable("ImagePoints");
                });

            modelBuilder.Entity("t5_back.Models.Photo", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Picture_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Event_ID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Image_ID")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Valide")
                        .HasColumnType("INTEGER");

                    b.HasKey("UUID");

                    b.HasIndex("Event_ID");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("t5_back.Models.Point_Equipement", b =>
                {
                    b.Property<Guid>("Point_ID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Equipement_ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Point_ID", "Equipement_ID");

                    b.HasIndex("Equipement_ID");

                    b.ToTable("PointEquipements");
                });

            modelBuilder.Entity("t5_back.Models.Image_Point", b =>
                {
                    b.HasOne("t5_back.Models.Photo", "Photo")
                        .WithMany("ImagePoints")
                        .HasForeignKey("Image_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("t5_back.Models.Point", "Point")
                        .WithMany("ImagePoints")
                        .HasForeignKey("Point_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.HasOne("t5_back.Models.Evenement", "Evenement")
                        .WithMany("Points")
                        .HasForeignKey("Event_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("t5_back.Models.Point_Equipement", b =>
                {
                    b.HasOne("t5_back.Models.Equipement", "Equipement")
                        .WithMany("PointEquipements")
                        .HasForeignKey("Equipement_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("t5_back.Models.Point", "Point")
                        .WithMany("PointEquipements")
                        .HasForeignKey("Point_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("t5_back.Models.Equipement", b =>
                {
                    b.Navigation("PointEquipements");
                });

            modelBuilder.Entity("t5_back.Models.Evenement", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("t5_back.Models.Photo", b =>
                {
                    b.Navigation("ImagePoints");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.Navigation("ImagePoints");

                    b.Navigation("PointEquipements");
                });
#pragma warning restore 612, 618
        }
    }
}
