// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using t5_back.Data;

#nullable disable

namespace t5_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("t5_back.Models.Action", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlanningId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SecurityZoneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("UUID");

                    b.HasIndex("PlanningId");

                    b.HasIndex("SecurityZoneId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("t5_back.Models.Area", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("EventId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("t5_back.Models.Employee", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("t5_back.Models.Equipment", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Length")
                        .HasColumnType("REAL");

                    b.Property<int?>("StorageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("t5_back.Models.Event", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("t5_back.Models.Picture", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("t5_back.Models.PicturePoint", b =>
                {
                    b.Property<Guid>("PictureId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PointId")
                        .HasColumnType("TEXT");

                    b.HasKey("PictureId", "PointId");

                    b.HasIndex("PointId");

                    b.ToTable("PicturePoints");
                });

            modelBuilder.Entity("t5_back.Models.Planning", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Validated")
                        .HasColumnType("INTEGER");

                    b.HasKey("UUID");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EventId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("t5_back.Models.RoutePath", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<float>("FastestEstimatedSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<float>("SlowestEstimatedSpeed")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("EventId");

                    b.ToTable("Paths");
                });

            modelBuilder.Entity("t5_back.Models.SecurityZone", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RemovalDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EventId");

                    b.ToTable("SecurityZones");
                });

            modelBuilder.Entity("t5_back.Models.Team", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("EventId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("t5_back.Models.TeamEmployee", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TeamEmployees");
                });

            modelBuilder.Entity("t5_back.Models.User", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("t5_back.Models.Action", b =>
                {
                    b.HasOne("t5_back.Models.Planning", "Planning")
                        .WithMany("Actions")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("t5_back.Models.SecurityZone", "SecurityZone")
                        .WithMany("Actions")
                        .HasForeignKey("SecurityZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");

                    b.Navigation("SecurityZone");
                });

            modelBuilder.Entity("t5_back.Models.Area", b =>
                {
                    b.HasOne("t5_back.Models.Event", "Event")
                        .WithMany("Areas")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("t5_back.Models.PicturePoint", b =>
                {
                    b.HasOne("t5_back.Models.Picture", "Picture")
                        .WithMany("PicturePoints")
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("t5_back.Models.Point", "Point")
                        .WithMany("PicturePoints")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("t5_back.Models.Planning", b =>
                {
                    b.HasOne("t5_back.Models.Team", "Team")
                        .WithOne("Planning")
                        .HasForeignKey("t5_back.Models.Planning", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.HasOne("t5_back.Models.Equipment", "Equipment")
                        .WithMany("Points")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("t5_back.Models.Event", "Event")
                        .WithMany("Points")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("t5_back.Models.RoutePath", b =>
                {
                    b.HasOne("t5_back.Models.Event", "Event")
                        .WithMany("Paths")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("t5_back.Models.SecurityZone", b =>
                {
                    b.HasOne("t5_back.Models.Equipment", "Equipment")
                        .WithMany("SecurityZones")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("t5_back.Models.Event", "Event")
                        .WithMany("SecurityZones")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("t5_back.Models.Team", b =>
                {
                    b.HasOne("t5_back.Models.Event", "Event")
                        .WithMany("Teams")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("t5_back.Models.TeamEmployee", b =>
                {
                    b.HasOne("t5_back.Models.Employee", "Employee")
                        .WithMany("TeamEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("t5_back.Models.Team", "Team")
                        .WithMany("TeamEmployees")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("t5_back.Models.Employee", b =>
                {
                    b.Navigation("TeamEmployees");
                });

            modelBuilder.Entity("t5_back.Models.Equipment", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("SecurityZones");
                });

            modelBuilder.Entity("t5_back.Models.Event", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Paths");

                    b.Navigation("Points");

                    b.Navigation("SecurityZones");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("t5_back.Models.Picture", b =>
                {
                    b.Navigation("PicturePoints");
                });

            modelBuilder.Entity("t5_back.Models.Planning", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("t5_back.Models.Point", b =>
                {
                    b.Navigation("PicturePoints");
                });

            modelBuilder.Entity("t5_back.Models.SecurityZone", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("t5_back.Models.Team", b =>
                {
                    b.Navigation("Planning");

                    b.Navigation("TeamEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
