export const Strings = {
  errors: {
    dbError: "Erreur DB",
    updateOrderError: "Erreur",
    updateOrderMessage: "Impossible de mettre à jour l'ordre des points.",
    fetchPointsMessage: "Impossible de récupérer les points.",
    fetchEventsMessage: "Impossible de récupérer les événements.",
  },
  points: {
    pointLabel: (order: number) => `Point ${order}`,
  },
  buttons: {
    simulateRoute: "Simuler l'itinéraire",
  },
  createPoint: {
    addComment: "Veuillez ajouter un commentaire",
    selectEquipment: "Veuillez sélectionner un type d'équipement",
    enterQuantity: "Veuillez entrer une quantité supérieure à 0",
    validatePosition: "Valider la position",
    editMarker: "Modifier le repère",
    selectEquipmentPlaceholder: "Sélectionnez un équipement",
    validate: "Valider",
  },
  event: {
    descriptionLabel: "Description :",
    dateLabel: "Date :",
    statusLabel: "Statut :",
    addPoints: "Ajouter des points",
    managePoints: "Gestion des points",
    exportEvent: "Exporter l'événement",
  },
  eventList: {
    resetDB: "Réinitialiser la base de données",
  },
  exportEvent: {
    invalidWebSocketURL: "✗ URL WebSocket invalide",
    cameraPermissionRequest: "Demande d'autorisation de la caméra...",
    cameraPermissionDenied: "Permission de caméra refusée",
    centerQRCode: "Centrez le QR code dans le cadre",
    cancel: "Annuler",
    exportInProgress: "Exportation en cours",
    transferComplete: "Transfert terminé",
    exportSuccess: "Exportation réussie",
    export: "Exportation",
    transferSuccess: "Transfert réussi !",
    transferError: "Erreur de transfert",
    back: "Retour",
  },
  importEvent: {
    centerQRCode: "Scannez le QR code pour importer",
    importInProgress: "Import en cours",
    importComplete: "Import terminé",
    importSuccess: "Import réussi",
    importError: "Erreur d'import",
    eventsReceived: "Événements reçus",
  },
  map: {
    locationPermissionDenied: "Permission de localisation refusée",
    noEquipment: "Aucun équipement",
    placePoint: "Placer un point",
  },
  pointPhotos: {
    cameraPermissionDenied: "Permission caméra refusée",
    takePhoto: "📸 Prendre une photo",
  },
  homeScreen: {
    accessApplication: "Entrer dans l'application",
    skipIntro: "Passer l'intro",
    welcomeTitle: "Bienvenue",
    welcomeSubtitle: "Capitale de l’Europe",
  },
};
