import { StyleSheet } from "react-native";

export const getStyles = (theme: string) =>
  StyleSheet.create({
    headerImage: {
      width: "40%",
      height: 30,
      alignSelf: "center",
    },
    container: {
      flex: 1,
      backgroundColor: theme === "light" ? "#f8f8fc" : "#20272f",
    },
    header: {
      backgroundColor: theme === "light" ? "#9EC54D" : "black",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingTop: 30,
      paddingBottom: 10,
      paddingLeft: 30,
      paddingRight: 14,
    },
    headerText: {
      color: theme === "light" ? "#fff" : "#EEE",
      fontWeight: "600",
      fontSize: 18,
    },
    listContainer: {
      padding: 20,
    },
    eventItem: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme === "light" ? "white" : "#444c56",
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOpacity: theme === "light" ? 0.05 : 0,
      shadowRadius: 3,
      elevation: theme === "light" ? 2 : 0,
    },
    avatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme === "light" ? "#E5E0FF" : "#333",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    avatarText: {
      fontWeight: "bold",
      color: theme === "light" ? "#6B5EFF" : "#AAA",
    },
    eventName: {
      flex: 1,
      fontSize: 16,
      color: theme === "light" ? "#000" : "#FFF",
    },
    fab: {
      position: "absolute",
      bottom: 25,
      right: 25,
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOpacity: theme === "light" ? 0.2 : 0,
      shadowRadius: 3,
      elevation: theme === "light" ? 4 : 0,
    },
    floatingButton: {
      position: "absolute",
      bottom: 30,
      left: 20,
      backgroundColor: theme === "light" ? "#0E47A1" : "#2196F3",
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    map: {
      height: "100%",
      width: "100%",
      flex: 1,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    emptyText: {
      fontSize: 18,
      color: theme === "light" ? "#666" : "#CCC",
    },
    currentPositionMarker: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: theme === "light" ? "rgba(30, 144, 255, 0.3)" : "#333",
      justifyContent: "center",
      alignItems: "center",
    },
    currentPositionDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: theme === "light" ? "#1E90FF" : "#2ad783",
      borderWidth: 2,
      borderColor: theme === "light" ? "white" : "#444c56",
    },
    pointMarker: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme === "light" ? "#E5E0FF" : "#333",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: theme === "light" ? "#6B5EFF" : "#AAA",
    },
    completedMarker: {
      backgroundColor: theme === "light" ? "#C8E6C9" : "#333",
      borderColor: theme === "light" ? "#4CAF50" : "#2ad783",
    },
    currentMarker: {
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      borderColor: theme === "light" ? "#A6CE39" : "#2ad783",
      transform: [{ scale: 1.2 }],
    },
    nextMarker: {
      backgroundColor: theme === "light" ? "#FFE0B2" : "#333",
      borderColor: theme === "light" ? "#FF9800" : "#555",
    },
    markerText: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme === "light" ? "#6B5EFF" : "#AAA",
    },
    completedMarkerText: {
      color: theme === "light" ? "#4CAF50" : "#2ad783",
    },
    infoPanel: {
      backgroundColor: theme === "light" ? "white" : "#444c56",
      padding: 20,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 5,
    },
    progressBar: {
      height: 6,
      backgroundColor: theme === "light" ? "#E0E0E0" : "#333",
      borderRadius: 3,
      marginBottom: 10,
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      borderRadius: 3,
    },
    progressText: {
      fontSize: 14,
      color: theme === "light" ? "#666" : "#CCC",
      marginBottom: 15,
      textAlign: "center",
    },
    currentPointInfo: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    pointDetails: {
      marginLeft: 12,
      flex: 1,
    },
    pointLabel: {
      fontSize: 12,
      color: theme === "light" ? "#666" : "#CCC",
      marginBottom: 2,
    },
    pointName: {
      fontSize: 18,
      fontWeight: "600",
      color: theme === "light" ? "#333" : "#EEE",
    },
    distanceInfo: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
      paddingLeft: 4,
    },
    distanceText: {
      fontSize: 16,
      fontWeight: "600",
      color: theme === "light" ? "#666" : "#CCC",
      marginLeft: 8,
    },
    nextPointInfo: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme === "light" ? "#E0E0E0" : "#555",
    },
    nextLabel: {
      fontSize: 12,
      color: theme === "light" ? "#999" : "#CCC",
      marginBottom: 2,
    },
    nextName: {
      fontSize: 14,
      color: theme === "light" ? "#666" : "#CCC",
    },
    controls: {
      padding: 20,
      backgroundColor: theme === "light" ? "white" : "#444c56",
    },
    startButton: {
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
      borderRadius: 12,
    },
    stopButton: {
      backgroundColor: theme === "light" ? "#FF6B6B" : "#333",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
      borderRadius: 12,
    },
    waitingContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
      borderRadius: 12,
      backgroundColor: theme === "light" ? "#F0F0F0" : "#333",
    },
    waitingText: {
      color: theme === "light" ? "#666" : "#CCC",
      fontSize: 18,
      fontWeight: "600",
      marginLeft: 8,
    },
    buttonText: {
      color: theme === "light" ? "white" : "#444c56",
      fontSize: 18,
      fontWeight: "600",
      textAlign: "center",
    },
    form: {
      padding: 20,
    },
    label: {
      fontSize: 16,
      marginBottom: 6,
      marginTop: 10,
      fontWeight: "500",
    },
    input: {
      backgroundColor: theme === "light" ? "#f2f2f2" : "#333",
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    inputCreatePoint: {
      backgroundColor: theme === "light" ? "#fff" : "#EEE",
      marginHorizontal: 15,
      padding: 15,
      borderRadius: 12,
      marginBottom: 20,
    },
    dateInput: {
      backgroundColor: theme === "light" ? "#f2f2f2" : "#333",
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 12,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    button: {
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      borderRadius: 20,
      alignItems: "center",
      paddingVertical: 14,
      marginTop: 25,
    },
    buttonTextBlack: {
      color: "black",
      fontSize: 16,
      fontWeight: "500",
    },
    dropdown: {
      margin: 15,
      backgroundColor: theme === "light" ? "#fff" : "#EEE",
      borderRadius: 12,
      marginTop: 4,
      borderWidth: 1,
      borderColor: theme === "light" ? "#fff" : "#EEE",
      overflow: "hidden",
      width: "92%",
      alignSelf: "center",
    },
    mapContainer: {
      backgroundColor: theme === "light" ? "#E8F5E9" : "#333",
      height: 250,
      width: "100%",
      position: "relative",
    },
    centerMarker: {
      position: "absolute",
      top: "50%",
      left: "50%",
      marginLeft: -24,
      marginTop: -48,
      zIndex: 1000,
    },
    editLocationButton: {
      backgroundColor: theme === "light" ? "#fff" : "#EEE",
      marginHorizontal: 15,
      marginTop: 10,
      marginBottom: 10,
      padding: 12,
      borderRadius: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: theme === "light" ? "#8DC63F" : "#2ad783",
    },
    editLocationButtonText: {
      color: theme === "light" ? "#8DC63F" : "#2ad783",
      fontSize: 16,
      fontWeight: "600",
    },
    inputComment: {
      backgroundColor: theme === "light" ? "#fff" : "#EEE",
      margin: 15,
      padding: 15,
      height: 120,
      textAlignVertical: "top",
      borderRadius: 12,
    },
    inputFake: {
      backgroundColor: theme === "light" ? "#fff" : "#EEE",
      marginHorizontal: 15,
      padding: 15,
      borderRadius: 12,
      marginBottom: 10,
      flexDirection: "row",
      justifyContent: "space-between",
    },

    validateButton: {
      backgroundColor: theme === "light" ? "#8DC63F" : "#2ad783",
      margin: 15,
      padding: 15,
      borderRadius: 12,
      alignItems: "center",
    },
    validateButtonText: {
      color: theme === "light" ? "#fff" : "#EEE",
      fontSize: 18,
    },
    content: {
      flex: 1,
    },
    titleContainer: {
      backgroundColor: theme === "light" ? "#F0F0F0" : "#333",
      paddingVertical: 16,
      paddingHorizontal: 20,
      alignItems: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme === "light" ? "#E0E0E0" : "#555",
    },
    eventTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: theme === "light" ? "#333" : "#EEE",
    },
    mapImage: {
      width: "100%",
      height: "100%",
    },
    detailsContainer: {
      backgroundColor: theme === "light" ? "white" : "#444c56",
      paddingHorizontal: 20,
      paddingVertical: 20,
      marginTop: 10,
    },
    detailRow: {
      marginBottom: 16,
    },
    detailLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: theme === "light" ? "#333" : "#EEE",
      marginBottom: 4,
    },
    detailValue: {
      fontSize: 14,
      color: theme === "light" ? "#666" : "#CCC",
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 20,
      gap: 12,
    },
    pointsButton: {
      flex: 1,
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: "center",
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    exportButton: {
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: "center",
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
      marginLeft: 20,
      marginRight: 20,
    },
    cameraContainer: {
      flex: 1,
      position: "relative",
    },
    camera: {
      flex: 1,
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "space-between",
    },
    overlayTop: {
      flex: 1,
      backgroundColor:
        theme === "light" ? "rgba(0, 0, 0, 0.6)" : "rgba(0,0,0,0.8)",
    },
    overlayMiddle: {
      flexDirection: "row",
      height: 300,
    },
    overlaySide: {
      flex: 1,
      backgroundColor:
        theme === "light" ? "rgba(0, 0, 0, 0.6)" : "rgba(0,0,0,0.8)",
    },
    scanArea: {
      width: 300,
      height: 300,
      position: "relative",
    },
    overlayBottom: {
      flex: 1,
      backgroundColor:
        theme === "light" ? "rgba(0,0,0,0.6)" : "rgba(0,0,0,0.8)",
      justifyContent: "center",
      alignItems: "center",
    },
    instructionText: {
      color: theme === "light" ? "#fff" : "#EEE",
      fontSize: 16,
      textAlign: "center",
      fontWeight: "500",
    },
    boutonAnnuler: {
      backgroundColor: "#cc2222ff",
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
      marginTop: 40,
      marginLeft: 20,
      marginRight: 20,
    },
    corner: {
      position: "absolute",
      width: 40,
      height: 40,
      borderColor: theme === "light" ? "#00ff00" : "#2ad783",
    },
    cornerTopLeft: {
      top: 0,
      left: 0,
      borderTopWidth: 4,
      borderLeftWidth: 4,
    },
    cornerTopRight: {
      top: 0,
      right: 0,
      borderTopWidth: 4,
      borderRightWidth: 4,
    },
    cornerBottomLeft: {
      bottom: 0,
      left: 0,
      borderBottomWidth: 4,
      borderLeftWidth: 4,
    },
    cornerBottomRight: {
      bottom: 0,
      right: 0,
      borderBottomWidth: 4,
      borderRightWidth: 4,
    },
    resultContainer: {
      flex: 1,
      backgroundColor: theme === "light" ? "#F5F5F5" : "#20272f",
      padding: 20,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme === "light" ? "#0E47A1" : "#2ad783",
      marginTop: 12,
    },
    urlContainer: {
      backgroundColor: theme === "light" ? "#fff" : "#444c56",
      padding: 16,
      borderRadius: 12,
      marginBottom: 24,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    urlLabel: {
      fontSize: 12,
      color: theme === "light" ? "#666" : "#CCC",
      marginBottom: 4,
      fontWeight: "600",
      textTransform: "uppercase",
    },
    urlText: {
      fontSize: 14,
      color: theme === "light" ? "#333" : "#EEE",
      fontFamily: "monospace",
    },
    loadingIcon: {
      alignSelf: "center",
      marginVertical: 30,
    },
    statusBox: {
      backgroundColor: theme === "light" ? "#E3F2FD" : "#333",
      padding: 16,
      borderRadius: 12,
      marginBottom: 20,
      borderLeftWidth: 4,
      borderLeftColor: theme === "light" ? "#0E47A1" : "#2ad783",
    },
    statusLabel: {
      fontSize: 16,
      color: theme === "light" ? "#0E47A1" : "#2ad783",
      fontWeight: "600",
      textAlign: "center",
    },
    progressContainer: {
      marginBottom: 30,
    },
    progressBarBackground: {
      height: 12,
      backgroundColor: theme === "light" ? "#E0E0E0" : "#333",
      borderRadius: 6,
      overflow: "hidden",
      marginBottom: 8,
    },
    progressBarFill: {
      height: "100%",
      backgroundColor: theme === "light" ? "#0E47A1" : "#2ad783",
      borderRadius: 6,
    },
    statsContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginTop: 10,
    },
    statCard: {
      backgroundColor: theme === "light" ? "#fff" : "#444c56",
      padding: 20,
      borderRadius: 12,
      alignItems: "center",
      flex: 1,
      marginHorizontal: 8,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    statNumber: {
      fontSize: 32,
      fontWeight: "bold",
      color: theme === "light" ? "#0E47A1" : "#2ad783",
      marginTop: 8,
    },
    statLabel: {
      fontSize: 12,
      color: theme === "light" ? "#666" : "#CCC",
      marginTop: 4,
      textAlign: "center",
    },
    successContainer: {
      flex: 1,
      justifyContent: "center",
    },
    successCard: {
      backgroundColor: theme === "light" ? "#fff" : "#444c56",
      padding: 30,
      borderRadius: 16,
      alignItems: "center",
      marginBottom: 24,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
    successTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme === "light" ? "#43A047" : "#2ad783",
      marginTop: 16,
      marginBottom: 8,
    },
    successMessage: {
      fontSize: 14,
      color: theme === "light" ? "#666" : "#CCC",
      textAlign: "center",
    },
    summaryContainer: {
      backgroundColor: theme === "light" ? "#fff" : "#444c56",
      padding: 20,
      borderRadius: 12,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    summaryTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme === "light" ? "#333" : "#EEE",
      marginBottom: 8,
      textAlign: "center",
    },
    summarySubtitle: {
      fontSize: 14,
      color: theme === "light" ? "#666" : "#AAA",
      marginBottom: 16,
      textAlign: "center",
      fontStyle: "italic",
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
    },
    summaryItem: {
      alignItems: "center",
      flex: 1,
    },
    summaryDivider: {
      width: 1,
      height: 60,
      backgroundColor: theme === "light" ? "#E0E0E0" : "#555",
    },
    summaryNumber: {
      fontSize: 28,
      fontWeight: "bold",
      color: theme === "light" ? "#0E47A1" : "#2ad783",
      marginTop: 8,
    },
    summaryLabel: {
      fontSize: 12,
      color: theme === "light" ? "#666" : "#CCC",
      marginTop: 4,
    },
    errorContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 30,
    },
    errorTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme === "light" ? "#E53935" : "#E57373",
      marginTop: 16,
      marginBottom: 8,
    },
    errorMessage: {
      fontSize: 14,
      color: theme === "light" ? "#666" : "#CCC",
      textAlign: "center",
    },
    retourButton: {
      backgroundColor: theme === "light" ? "#0E47A1" : "#2ad783",
      paddingVertical: 16,
      paddingHorizontal: 32,
      borderRadius: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 30,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 5,
    },
    retourButtonText: {
      color: theme === "light" ? "#fff" : "#20272f",
      fontSize: 16,
      fontWeight: "600",
      marginLeft: 8,
    },
    Marker: { width: 200, height: 200 },
    markerContainer: {
      width: 39,
      height: 39,
      paddingVertical: 6,
      backgroundColor: theme === "light" ? "white" : "#444c56",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme === "light" ? "#9EC54D" : "#2ad783",
      alignItems: "center",
      justifyContent: "center",
    },
    markerQty: {
      fontSize: 10,
      fontWeight: "700",
      color: theme === "light" ? "#333" : "#EEE",
    },
    markerType: {
      fontSize: 8,
      color: theme === "light" ? "#555" : "#CCC",
      textAlign: "center",
    },
    addButton: {
      backgroundColor: theme === "light" ? "#9EC54D" : "#2ad783",
      padding: 15,
      margin: 20,
      borderRadius: 10,
      alignItems: "center",
    },
    addButtonText: {
      color: theme === "light" ? "#fff" : "#20272f",
      fontSize: 18,
      fontWeight: "500",
    },
    photoContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      paddingHorizontal: 20,
    },
    photo: { width: 110, height: 110, borderRadius: 8 },

    pointItemContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    reorderButtons: {
      marginRight: 8,
      justifyContent: "center",
    },
    reorderButton: {
      padding: 4,
    },
    pointItem: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme === "light" ? "white" : "#444c56",
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 2,
    },
    bottomButtonContainer: {
      padding: 20,
      paddingBottom: 25,
      backgroundColor: theme === "light" ? "#f8f8fc" : "#20272f",
    },
    simulateButton: {
      backgroundColor: theme === "light" ? "#A6CE39" : "#2ad783",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
      borderRadius: 12,
      shadowColor: theme === "light" ? "#000" : "#FFF",
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 4,
    },
    buttonIcon: {
      marginRight: 8,
    },
    simulateButtonText: {
      color: theme === "light" ? "white" : "#20272f",
      fontSize: 16,
      fontWeight: "600",
    },
  });
